/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_jasa_pengiriman_barang;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class form_petugas extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet rspetugas;
private String sql="";
private String id,nama,jabatan,alamat,telepon,pengirim,status,penerima,alamat2;

    /**
     * Creates new form form_petugas
     */
    public form_petugas() {
        initComponents();
        koneksikan ();
        tampildata("select * from tb_petugas"); 
    }

    
    
    private void koneksikan() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jasa_pengiriman_barang", "root", "");
            System.out.println("Next");
            JOptionPane.showMessageDialog(null, "koneksi berhasil");
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            System.out.println("Koneksi Gagal \n" + e);
        }
    }
    private void tampildata(String sql){
    DefaultTableModel datalist = new DefaultTableModel();
    datalist.addColumn("No");
    datalist.addColumn("ID Petugas");
    datalist.addColumn("Nama Petugas");
    datalist.addColumn("Jabatan");
    datalist.addColumn("Status");
    datalist.addColumn("pengirim");
    datalist.addColumn("Alamat Pengirim");
    datalist.addColumn("Penerima");
    datalist.addColumn("Alamat Penerima");
    datalist.addColumn("Telepon");
    
    try{
        int i = 1 ;
        st=con.createStatement();
        rspetugas=st.executeQuery("select * from tb_petugas");
        while (rspetugas.next()){
                datalist.addRow(new Object[]{
            (""+i++),rspetugas.getString(1),
            rspetugas.getString(2), 
            rspetugas.getString(3),
            rspetugas.getString(4),
            rspetugas.getString(5),
            rspetugas.getString(6),
            rspetugas.getString(7),
            rspetugas.getString(8),
            rspetugas.getString(9)
        });
        gridpetugas.setModel(datalist);
        }
        
    }catch (Exception e){
    }    
}
    
    
    
    private void kosongkan(){
        txtid.setText("");
        txtnama.setText("");
        txtpengirim.setText("");
        txtalamat2.setText("");
        txtstatus.setSelectedItem("");
        txtpenerima.setText("");
        txtjabatan.setSelectedItem("");
        txtalamat.setText("");
        txttelepon.setText("");
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        gridpetugas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtalamat2 = new javax.swing.JTextArea();
        txtpengirim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtpenerima = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtstatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel1.setText("ID Petugas");

        jLabel2.setText("Nama Petugas");

        jLabel3.setText("Jabatan");

        jLabel4.setText("Telepon");

        jLabel5.setText("Alamat");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kurir", " " }));
        txtjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjabatanActionPerformed(evt);
            }
        });

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        gridpetugas.setBackground(new java.awt.Color(51, 204, 255));
        gridpetugas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridpetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Petugas", "Nama Petugas", "Jabatan", "Status", "Pengirim", "Alamat Pengirim", "Penerima", "Alamat Penerima", "Telepon"
            }
        ));
        gridpetugas.setToolTipText("");
        gridpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridpetugasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(gridpetugas);

        jLabel6.setText("Alamat");

        jLabel7.setText("Pengirim");

        txtalamat2.setColumns(20);
        txtalamat2.setRows(5);
        jScrollPane2.setViewportView(txtalamat2);

        jLabel8.setText("Penerima");

        jLabel10.setText("Status");

        txtstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all", "DE", "ST", "OD", "OK", "RT", " " }));
        txtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel5))
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtpengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(625, 625, 625))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnsimpan)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnubah)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnhapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnbatal)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnkeluar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan)
                            .addComponent(btnubah)
                            .addComponent(btnhapus)
                            .addComponent(btnbatal)
                            .addComponent(btnkeluar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        id=String.valueOf(txtid.getText());
        nama=String.valueOf(txtnama.getText());
        pengirim=String.valueOf(txtpengirim.getText());
        status=txtstatus.getItemAt(txtstatus.getSelectedIndex()).toString();
        penerima=String.valueOf(txtpenerima.getText());
        alamat2=String.valueOf(txtalamat2.getText());
        jabatan=txtjabatan.getItemAt(txtjabatan.getSelectedIndex()).toString();
        alamat=String.valueOf(txtalamat.getText());
        telepon=String.valueOf(txttelepon.getText());
       
            try{
                sql="insert into tb_petugas (id_petugas,nama_petugas,jabatan,Status,pengirim,alamat_pengirim,Penerima,alamat_penerima,telepon)values("
                +"'"+id+"','"+nama+"','"+jabatan+"','"+status+"','"+pengirim+"','"+alamat+"','"+penerima+"','"+alamat2+"','"+telepon+"')";
                st=con.createStatement();
                st.execute(sql);
                tampildata("select * from tb_petugas");
                JOptionPane.showMessageDialog(null,"data berhasil disimpan");
                }catch (SQLException | HeadlessException e){
               JOptionPane.showMessageDialog(null,"data gagal disimpan \n"+e.getMessage());
               }kosongkan();
      
     
         
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        id=String.valueOf(txtid.getText());
        nama=String.valueOf(txtnama.getText());
        pengirim=String.valueOf(txtpengirim.getText());
        status=txtstatus.getItemAt(txtstatus.getSelectedIndex()).toString();
        penerima=String.valueOf(txtpenerima.getText());
        alamat2=String.valueOf(txtalamat2.getText());
        jabatan=txtjabatan.getItemAt(txtjabatan.getSelectedIndex()).toString();
        alamat=String.valueOf(txtalamat.getText());
        telepon=String.valueOf(txttelepon.getText());
        if(JOptionPane.showConfirmDialog(this,"Apakah data ini mau diubah","konfirmasi",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
            JOptionPane.YES_OPTION){
            try{
                sql="update tb_petugas set nama_petugas'"+nama+"',"
                        +"jabatan='"+jabatan+"',alamat ='"+alamat+"' where id_petugas='"+id+"'";
                st=con.createStatement();
                st.execute(sql);
                tampildata("select * from tb_petugas");
                JOptionPane.showMessageDialog(null,"data berhasil diubah");
                kosongkan();
                
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"data gagal diubah \n"+e.getMessage());
            }
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
     id=String.valueOf(txtid.getText());
        if(JOptionPane.showConfirmDialog(this,"Apakah anda yakin menghapus data ini","konfirmasi",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
            JOptionPane.YES_OPTION)
            {
                try{
                    sql="delete from tb_petugas where id_petugas='"+id+"'";
                    st=con.createStatement();
                    st.execute(sql);
                    tampildata("select * from tb_petugas");
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosongkan();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,"data gagal dihapus \n"+e.getMessage());
                }
            }       
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(1);
        
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjabatanActionPerformed

    private void gridpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridpetugasMouseClicked
        // TODO add your handling code here:
        txtid.setText(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),1)));
          txtnama.setText(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),2)));
            txtjabatan.setSelectedItem(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),3)));
              txtstatus.setSelectedItem(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),4)));
                txtpengirim.setText(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),5)));
                    txtalamat.setText(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),6)));
                         txtpenerima.setText(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),7)));
                            txtalamat2.setText(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),8)));
                                 txttelepon.setText(String.valueOf(gridpetugas.getValueAt(gridpetugas.getSelectedRow(),9)));
                
               

    }//GEN-LAST:event_gridpetugasMouseClicked

    private void txtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JTable gridpetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextArea txtalamat2;
    private javax.swing.JTextField txtid;
    private javax.swing.JComboBox<String> txtjabatan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpenerima;
    private javax.swing.JTextField txtpengirim;
    private javax.swing.JComboBox<String> txtstatus;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
