/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_jasa_pengiriman_barang;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;


/**
 *
 * @author User
 */
public class form_pengiriman_barang extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet rskirim;
private ResultSet rspetugas;
private ResultSet rspaket;
private ResultSet rspengirim;
private String sql="";
private String id,resi,tujuan,idpetugas,nopengirim,penerima,alamat,telepon,telepon2,paket,isi,namapetugas,jabatan,namapengirim,alamatpengirim;
private int berat,biaya,asuransi,total;


 

    /**
     * Creates new form form_pengiriman_barang
     */
    public form_pengiriman_barang() {
    initComponents();
    koneksikan();
    daftarpetugas();
    daftarpaket();
        
    }

 private void koneksikan(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jasa_pengiriman_barang","root","");
            System.out.println("Koneksi berhasil");
            JOptionPane.showMessageDialog(null, "koneksi berhasil");
        } catch (ClassNotFoundException | SQLException | HeadlessException e) {
            System.out.println("Koneksi Gagal \n"+e);
        }
    }

private void tampildata(String sql){
    DefaultTableModel datalist = new DefaultTableModel();
    datalist.addColumn("No");
    datalist.addColumn("NO Resi");
    datalist.addColumn("tanggal");
    datalist.addColumn("Tujuan");
    datalist.addColumn("ID Petugas");
    datalist.addColumn("NO Pengirim");
    datalist.addColumn("paket_type");
    datalist.addColumn("Penerima");
    datalist.addColumn("Alamat");
    datalist.addColumn("Paket");
    datalist.addColumn("Berat");
    datalist.addColumn("Biaya");
    datalist.addColumn("Asuransi");
    datalist.addColumn("Isi Paket");
    datalist.addColumn("Total");
    try{
        int i = 1 ;
        st=con.createStatement();
        rskirim=st.executeQuery("select * from tb_pengiriman_barang");
        while (rskirim.next()){
                datalist.addRow(new Object[]{
            (""+i++),rskirim.getString(1),
            rskirim.getString(2), 
            rskirim.getString(3),
            rskirim.getString(4),
            rskirim.getString(5),
            rskirim.getString(6),
            rskirim.getString(7),
            rskirim.getString(8),
            rskirim.getString(9),
            rskirim.getString(10),
            rskirim.getString(11),
            rskirim.getString(12),
            rskirim.getString(13),
            rskirim.getString(14),
        });
        gridpengiriman.setModel(datalist);
        }
        
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Gagal Tampil \n"+e.getMessage());
    }    
}

private void kosongkan(){
    txtresi.setText("");
    txtkotatujuan.setText("");
    txtnamapetugas.setText("");
    txtjabatan.setText("");
    txtnamapengirim.setText("");
    txtalamatpengirim.setText("");
    txtisipaket.setText("");
    txtpenerima.setText("");
    txtalamatpenerima.setText("");
    txttelepon.setText("");
    txtbiaya.setText("");
    txtasuransi.setText("");
    txtberat.setText("");
    txttotal.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtresi = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        txtnamapetugas = new javax.swing.JTextField();
        txtkotatujuan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtnamapengirim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txttelepon = new javax.swing.JTextField();
        txtpenerima = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatpenerima = new javax.swing.JTextArea();
        txttype = new javax.swing.JComboBox<>();
        txtbiaya = new javax.swing.JTextField();
        txtasuransi = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtberat = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtisipaket = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        gridpengiriman = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnhitung = new javax.swing.JButton();
        txtidpetugas = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtalamatpengirim = new javax.swing.JTextArea();
        txttanggal = new com.toedter.calendar.JDateChooser();

        jLabel16.setText("Asuransi");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Resi");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Kota Tujuan");

        jLabel5.setText("ID Petugas");

        jLabel7.setText("Nama");

        jLabel8.setText("Alamat");

        jLabel10.setText("Biaya");

        jLabel11.setText("Paket Type");

        jLabel13.setText("Asuransi");

        txtnamapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapetugasActionPerformed(evt);
            }
        });

        txtkotatujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkotatujuanActionPerformed(evt);
            }
        });

        jLabel17.setText("Nama Petugas");

        jLabel18.setText("Jabatan");

        jLabel9.setText("Penerima");

        jLabel14.setText("Alamat");

        jLabel15.setText("Telepon");

        txtalamatpenerima.setColumns(20);
        txtalamatpenerima.setRows(5);
        jScrollPane1.setViewportView(txtalamatpenerima);

        txttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Kilat", "Express", " " }));
        txttype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txttypeItemStateChanged(evt);
            }
        });
        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });

        jLabel19.setText("Berat");

        jLabel20.setText("Total");

        jLabel12.setText("Isi Paket");

        txtisipaket.setColumns(20);
        txtisipaket.setRows(5);
        jScrollPane3.setViewportView(txtisipaket);

        gridpengiriman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridpengiriman.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                gridpengirimanAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        gridpengiriman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridpengirimanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(gridpengiriman);

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        txtidpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kurir" }));
        txtidpetugas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtidpetugasItemStateChanged(evt);
            }
        });
        txtidpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpetugasActionPerformed(evt);
            }
        });

        txtalamatpengirim.setColumns(20);
        txtalamatpengirim.setRows(5);
        jScrollPane5.setViewportView(txtalamatpengirim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtresi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel5))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamapetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtasuransi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnhitung))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(35, 35, 35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(35, 35, 35)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnamapengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkotatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnsimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnhapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnubah))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnkeluar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnbatal)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtidpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtnamapetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtasuransi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhitung))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtkotatujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnamapengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnsimpan)
                                            .addComponent(btnhapus)
                                            .addComponent(btnubah)
                                            .addComponent(btnkeluar)
                                            .addComponent(btnbatal))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addComponent(jLabel20)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        resi=String.valueOf(txtresi.getText());
        tujuan=String.valueOf(txtkotatujuan.getText());
        idpetugas=txtidpetugas.getItemAt(txtidpetugas.getSelectedIndex()).toString();
        namapetugas=String.valueOf(txtnamapetugas.getText());
        jabatan=String.valueOf(txtjabatan.getText());
        namapengirim=String.valueOf(txtnamapengirim.getText());
        alamat=String.valueOf(txtalamatpengirim.getText());
        penerima=String.valueOf(txtpenerima.getText());
        alamat=String.valueOf(txtalamatpenerima.getText());
        telepon=String.valueOf(txttelepon.getText());
        biaya=Integer.parseInt(txtbiaya.getText());
        berat=Integer.parseInt(txtberat.getText());
        total=Integer.parseInt(txttotal.getText());
        isi=String.valueOf(txtisipaket.getText());
        
            try{
                    sql="insert into tb_pengiriman_barang(no_resi,tanggal,kota_tujuan,id_petugas,no_pengirim,penerima,alamat,telepon,paket_type,berat,biaya,asuransi,isi_paket,total)"
                            + "values ('" +resi+"','"+txttanggal+"','"+tujuan+"','"+idpetugas+"','"+namapetugas+"',"
                            +"'"+jabatan+"','"+namapengirim+"','"+alamat+"','"+penerima+"',"
                            +"'"+alamat+"','"+telepon+"','"+biaya+"','"+asuransi+"','"+berat+"',"
                            +"'"+total+"','"+isi+"')";
                    st=con.createStatement();
                    st.execute(sql);
                    tampildata("select *from tb_pengiriman_barang");
                    JOptionPane.showMessageDialog(null,"data berhasil disimpan");              
            }catch (Exception e){
               JOptionPane.showMessageDialog(null,"data gagal disimpan \n"+e.getMessage());
               }kosongkan();
     
                         
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
         // TODO add your handling code here:
         resi=String.valueOf(txtresi.getText());
        if(JOptionPane.showConfirmDialog(this,"Apakah anda yakin menghapus data ini","konfirmasi",
            JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE)==
            JOptionPane.YES_OPTION)
            {
                try{
                    sql="delete from tb_pengiriman_barang where no_resi='"+resi+"'";
                    st=con.createStatement();
                    st.execute(sql);
                    tampildata("select * from tb_pengiriman_barang");
                    JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                    kosongkan();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,"data gagal dihapus \n"+e.getMessage());
                }
            }
          
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        resi=String.valueOf(txtresi.getText());
        tujuan=String.valueOf(txtkotatujuan.getText());
        idpetugas=txtidpetugas.getItemAt(txtidpetugas.getSelectedIndex()).toString();
        namapetugas=String.valueOf(txtnamapetugas.getText());
        jabatan=String.valueOf(txtjabatan.getText());
        namapengirim=String.valueOf(txtnamapengirim.getText());
        alamat=String.valueOf(txtalamatpengirim.getText());
        penerima=String.valueOf(txtpenerima.getText());
        alamat=String.valueOf(txtalamatpenerima.getText());
        telepon=String.valueOf(txttelepon.getText());
        biaya=Integer.parseInt(txtbiaya.getText());
        berat=Integer.parseInt(txtberat.getText());
        total=Integer.parseInt(txttotal.getText());
        isi=String.valueOf(txtisipaket.getText());
        
            try{
                    sql="update tb_pengiriman_barang set kota_tujuan='"+tujuan+"',id_petugas='"+idpetugas+"',"
                            +"',penerima='"+penerima+"',"
                            + "alamat='"+alamat+"',telepon='"+telepon+"',paket_type='"+paket+"',"
                            + "berat='"+berat+"',biaya='"+biaya+"',asuransi='"+asuransi+"',isi_paket='"+isi+"',"
                            + "total='"+total+"' where no_resi='"+resi+"'";
                            
                    st=con.createStatement();
                    st.execute(sql);
                    tampildata("select *from tb_pengiriman_barang");
                    JOptionPane.showMessageDialog(null,"data berhasil diubah");              
            }catch (Exception e){
               JOptionPane.showMessageDialog(null,"data gagal diubah \n"+e.getMessage());
               }kosongkan();
     
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
 kosongkan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(1);
  
        
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void gridpengirimanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridpengirimanMouseClicked
        // TODO add your handling code here:
        txtresi.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),1)));
        txtkotatujuan.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),2)));
        txtidpetugas.setSelectedItem(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),3)));
        txtnamapetugas.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),4)));
        txtjabatan.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),5)));
        txtnamapengirim.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),6)));
        txtalamatpengirim.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),7)));
        txttype.setSelectedItem(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),8)));
        txtpenerima.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),9)));
        txtalamatpenerima.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),10)));
        txttelepon.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),11)));
        txtisipaket.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),12)));
        txtbiaya.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),13)));
        txtberat.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),14)));
        txtasuransi.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),15)));
        txttotal.setText(String.valueOf(gridpengiriman.getValueAt(gridpengiriman.getSelectedRow(),16)));
      
        
    }//GEN-LAST:event_gridpengirimanMouseClicked


   
    private void txtidpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpetugasActionPerformed
     
    }//GEN-LAST:event_txtidpetugasActionPerformed


    private void gridpengirimanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_gridpengirimanAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_gridpengirimanAncestorAdded

    private void txtkotatujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkotatujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkotatujuanActionPerformed

    private void txtidpetugasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtidpetugasItemStateChanged
        // TODO add your handling code here:
        try {
            sql="select * from tb_petugas where "
                    + "id_petugas='" +txtidpetugas.getSelectedItem()+ "'";
            st=con.createStatement();
            rspetugas=st.executeQuery(sql);
            while (rspetugas.next()) {
                txtnamapetugas.setText(rspetugas.getString(2));
                txtjabatan.setText(rspetugas.getString(3));
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Gagal Tampil \n"+e.getMessage());
        }
    
    }//GEN-LAST:event_txtidpetugasItemStateChanged

     private void daftarpetugas(){
    txtidpetugas.removeAllItems();
    txtidpetugas.addItem("Pilih");
    try{
        String Sql="select * from tb_petugas";
        Statement st=con.createStatement();
        rspetugas = st.executeQuery(sql);
        while(rspetugas.next()){
            String idpetugas=rspetugas.getString("id_petugas");
            txtidpetugas.addItem("id_petugas");
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,
                "gagal menampilkan ID petugas \n"+e.getMessage());
    }
}
    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void txttypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txttypeItemStateChanged
       try {
            sql="select * from tb_jenis_paket where "
                    + "paket_type='" +txttype.getSelectedItem()+ "'";
            st=con.createStatement();
            rspengirim=st.executeQuery(sql);
            while (rspengirim.next()) {
                txtbiaya.setText(rspengirim.getString(2));
                txtasuransi.setText(rspengirim.getString(3));
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Gagal Tampil \n"+e.getMessage());
        }
        
    }//GEN-LAST:event_txttypeItemStateChanged

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhitungActionPerformed

    private void txtnamapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapetugasActionPerformed

    private void daftarpaket(){
    txttype.removeAllItems();
    txttype.addItem("Pilih");
    try{
        String Sql="select * from tb_jenis_paket";
        Statement st=con.createStatement();
        rspengirim=st.executeQuery(sql);
        while(rspengirim.next()){
            String aliasid=rspengirim.getString("id_paket");
            txttype.addItem(aliasid);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "gagal tampil \n"+e.getMessage());
    }

    
}  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pengiriman_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pengiriman_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pengiriman_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pengiriman_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pengiriman_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JTable gridpengiriman;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextArea txtalamatpenerima;
    private javax.swing.JTextArea txtalamatpengirim;
    private javax.swing.JTextField txtasuransi;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txtbiaya;
    private javax.swing.JComboBox<String> txtidpetugas;
    private javax.swing.JTextArea txtisipaket;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtkotatujuan;
    private javax.swing.JTextField txtnamapengirim;
    private javax.swing.JTextField txtnamapetugas;
    private javax.swing.JTextField txtpenerima;
    private javax.swing.JTextField txtresi;
    private com.toedter.calendar.JDateChooser txttanggal;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JTextField txttotal;
    private javax.swing.JComboBox<String> txttype;
    // End of variables declaration//GEN-END:variables
}
